name: Build Ionic Android APK

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'ionic_ui_templates/**'
      - '!ionic_ui_templates/**/*.md'
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Web environment to install packages.
      - name: Setup Web environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Setup Java environment in order to build the Android app.
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install packages
        run: npm install --legacy-peer-deps
        working-directory: ionic_ui_templates

      - name: Build the ionic project for Android
        run: ionic capacitor build android --prod --no-open
        working-directory: ionic_ui_templates

      - name: Build Android debug APK
        run: ./gradlew assembleDebug
        working-directory: ionic_ui_templates/android

      - name: Save apk file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ionic-actions-test
          path: ionic_ui_templates/android/app/build/outputs/apk/debug/app-debug.apk